[11:39:05] [DEBUG] Running client sanity checks...
[11:39:06] [DEBUG] No setup function found in play
[11:39:06] [DEBUG] Found extension class Music in play: Attempting to load
[11:39:06] [DEBUG] Added callback: Music._menu
[11:39:06] [DEBUG] Added callback: Music._pause
[11:39:06] [DEBUG] Added callback: Music._resume
[11:39:06] [DEBUG] Added callback: Music._skip
[11:39:06] [DEBUG] Added callback: Music._stop
[11:39:06] [DEBUG] Added callback: Music.play
[11:39:06] [DEBUG] Loaded Extension: play
[11:39:07] [DEBUG] No setup function found in askbard
[11:39:07] [DEBUG] Found extension class Bard in askbard: Attempting to load
[11:39:07] [DEBUG] Added callback: Bard._askbard
[11:39:07] [DEBUG] Added callback: Bard._endbard
[11:39:07] [DEBUG] Added callback: Bard.set_bard_channel
[11:39:07] [DEBUG] Loaded Extension: askbard
[11:39:07] [DEBUG] No setup function found in noi_chu
[11:39:07] [DEBUG] Found extension class NoiChu in noi_chu: Attempting to load
[11:39:07] [DEBUG] Added callback: NoiChu._reset
[11:39:07] [DEBUG] Added callback: NoiChu._world_setup
[11:39:07] [DEBUG] Loaded Extension: noi_chu
[11:39:07] [DEBUG] No setup function found in db_refesh
[11:39:07] [DEBUG] Found extension class Database in db_refesh: Attempting to load
[11:39:07] [DEBUG] Loaded Extension: db_refesh
[11:39:07] [DEBUG] No setup function found in help
[11:39:07] [DEBUG] Found extension class Help in help: Attempting to load
[11:39:07] [DEBUG] Added callback: Help.help
[11:39:07] [DEBUG] Loaded Extension: help
[11:39:07] [DEBUG] Loaded Extension: interactions.ext.jurigged
[11:39:07] [DEBUG] Added callback: __join
[11:39:07] [DEBUG] Added callback: __leave
[11:39:07] [DEBUG] Added callback: _about
[11:39:07] [DEBUG] Added callback: _refresh
[11:39:07] [DEBUG] Added callback: _setup
[11:39:07] [DEBUG] Added callback: on_start
[11:39:07] [DEBUG] 6 callbacks have been loaded from __main__.
[11:39:07] [DEBUG] Added callback: _disconnect
[11:39:07] [DEBUG] Added callback: _on_websocket_ready
[11:39:07] [DEBUG] Added callback: on_autocomplete_completion
[11:39:07] [DEBUG] Added callback: on_autocomplete_error
[11:39:07] [DEBUG] Added callback: on_command_completion
[11:39:07] [DEBUG] Added callback: on_command_error
[11:39:07] [DEBUG] Added callback: on_component_completion
[11:39:07] [DEBUG] Added callback: on_component_error
[11:39:07] [DEBUG] Added callback: on_error
[11:39:07] [DEBUG] Added callback: on_modal_completion
[11:39:07] [DEBUG] Added callback: on_modal_error
[11:39:07] [DEBUG] Added callback: on_resume
[11:39:07] [DEBUG] 12 callbacks have been loaded from Client.
[11:39:07] [DEBUG] Attempting to login
[11:39:07] [DEBUG] Caching ingested rate limit data for: 78bb8553d9352a5a2f89f9def401287a
[11:39:07] [DEBUG] GET /users/@me Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[11:39:07] [DEBUG] GET /users/@me Received 200 :: [0/1000 calls remaining]
[11:39:08] [DEBUG] Caching ingested rate limit data for: d28a133af187e91d71d96a223467ce49
[11:39:08] [DEBUG] GET /oauth2/applications/@me Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[11:39:08] [DEBUG] GET /oauth2/applications/@me Received 200 :: [0/1000 calls remaining]
[11:39:08] [WARNING] Setting sync_ext to True by default for syncing changes
[11:39:08] [INFO] Loading jurigged
[11:39:08] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\Main.py
[11:39:08] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\play.py
[11:39:08] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\embed.py
[11:39:08] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\askbard.py
[11:39:08] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\noi_chu.py
[11:39:08] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\db_refesh.py
[11:39:08] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\help.py
[11:39:08] [DEBUG] Caching ingested rate limit data for: 0a6d458104b103c7be293cc9b284d9ee
[11:39:08] [DEBUG] GET /gateway Received 200 :: [99/100 calls remaining]
[11:39:08] [INFO] Shard ID 0 | Starting Shard
[11:39:08] [INFO] Shard ID 0 | Shard is attempting to connect to gateway...
[11:39:08] [DEBUG] Shard ID 0 | Identification payload sent to gateway, requesting intents: 3407613
[11:39:09] [DEBUG] Sending heartbeat every 41.25 seconds
[11:39:09] [DEBUG] Sending data to websocket: {"op": 1, "d": null}
[11:39:09] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:39:09] [INFO] Shard ID 0 | Gateway connection established
[11:39:09] [DEBUG] Shard ID 0 | Session ID: 3bee2a8cd44d182368c6866b2e2185d2 Trace: ['["gateway-prd-us-east1-d-jm1c",{"micros":58067,"calls":["id_created",{"micros":2028,"calls":[]},"session_lookup_time",{"micros":4361,"calls":[]},"session_lookup_finished",{"micros":15,"calls":[]},"discord-sessions-prd-2-3",{"micros":51082,"calls":["start_session",{"micros":42676,"calls":["discord-api-dc69f8484-z9hss",{"micros":37410,"calls":["get_user",{"micros":9371},"get_guilds",{"micros":3071},"send_scheduled_deletion_message",{"micros":12},"guild_join_requests",{"micros":766},"authorized_ip_coro",{"micros":10}]}]},"starting_guild_connect",{"micros":67,"calls":[]},"presence_started",{"micros":328,"calls":[]},"guilds_started",{"micros":159,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":7817,"calls":[]},"connect_finished",{"micros":7823,"calls":[]},"build_ready",{"micros":25,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":0,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}]']
[11:39:09] [DEBUG] Dispatching Event: websocket_ready
[11:39:09] [DEBUG] Dispatching Event: guild_join
[11:39:09] [DEBUG] Dispatching Event: guild_join
[11:39:09] [DEBUG] Dispatching Event: guild_join
[11:39:09] [DEBUG] Dispatching Event: guild_join
[11:39:09] [DEBUG] Dispatching Event: guild_join
[11:39:09] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:39:09] [DEBUG] Caching ingested rate limit data for: dd84d9818020c27975c0d5ab4a794d44
[11:39:09] [DEBUG] GET /applications/{application_id}/commands Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[11:39:09] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [0/1000 calls remaining]
[11:39:09] [DEBUG] Waiting for bucket dd84d9818020c27975c0d5ab4a794d44 to unlock.
[11:39:10] [DEBUG] Caching ingested rate limit data for: dd84d9818020c27975c0d5ab4a794d44
[11:39:10] [DEBUG] GET /applications/{application_id}/commands Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[11:39:10] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [0/1000 calls remaining]
[11:39:10] [DEBUG] 0 is already up-to-date with 15 commands.
[11:39:10] [DEBUG] Sync of 1 scopes took 0.8742583999992348 seconds
[11:39:10] [DEBUG] Dispatching Event: startup
[11:39:10] [DEBUG] Sending data to websocket: {"op": 3, "d": {"since": 1702960750243, "activities": [{"name": "/help for helpful", "type": 0}], "status": "idle", "afk": false}}
[11:39:23] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\live.py", line 104, in refresh
    cf.refresh()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1118, in refresh
    new_source = self.read_source()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1065, in read_source
    source = f.read()
             ^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1258.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1896: character maps to <undefined>
[11:39:24] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\live.py", line 104, in refresh
    cf.refresh()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1118, in refresh
    new_source = self.read_source()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1065, in read_source
    source = f.read()
             ^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1258.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1896: character maps to <undefined>
[11:39:35] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\live.py", line 104, in refresh
    cf.refresh()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1118, in refresh
    new_source = self.read_source()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1065, in read_source
    source = f.read()
             ^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1258.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1896: character maps to <undefined>
[11:39:36] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\live.py", line 104, in refresh
    cf.refresh()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1118, in refresh
    new_source = self.read_source()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1065, in read_source
    source = f.read()
             ^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1258.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1896: character maps to <undefined>
[11:39:46] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\live.py", line 104, in refresh
    cf.refresh()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1118, in refresh
    new_source = self.read_source()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1065, in read_source
    source = f.read()
             ^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1258.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 2817: character maps to <undefined>
[11:39:46] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\live.py", line 104, in refresh
    cf.refresh()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1118, in refresh
    new_source = self.read_source()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1065, in read_source
    source = f.read()
             ^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1258.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 2817: character maps to <undefined>
[11:39:50] [DEBUG] Sending data to websocket: {"op": 1, "d": 6}
[11:39:50] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:39:50] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:40:19] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\live.py", line 104, in refresh
    cf.refresh()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1118, in refresh
    new_source = self.read_source()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1065, in read_source
    source = f.read()
             ^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1258.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 2817: character maps to <undefined>
[11:40:20] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\live.py", line 104, in refresh
    cf.refresh()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1118, in refresh
    new_source = self.read_source()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1065, in read_source
    source = f.read()
             ^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1258.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 2817: character maps to <undefined>
[11:40:25] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\live.py", line 104, in refresh
    cf.refresh()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1118, in refresh
    new_source = self.read_source()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1065, in read_source
    source = f.read()
             ^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1258.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 2817: character maps to <undefined>
[11:40:26] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\live.py", line 104, in refresh
    cf.refresh()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1118, in refresh
    new_source = self.read_source()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1065, in read_source
    source = f.read()
             ^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1258.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 2817: character maps to <undefined>
[11:40:31] [DEBUG] Sending data to websocket: {"op": 1, "d": 6}
[11:40:31] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:40:31] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:40:35] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\live.py", line 104, in refresh
    cf.refresh()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1118, in refresh
    new_source = self.read_source()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1065, in read_source
    source = f.read()
             ^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1258.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 2818: character maps to <undefined>
[11:40:36] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\live.py", line 104, in refresh
    cf.refresh()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1118, in refresh
    new_source = self.read_source()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 1065, in read_source
    source = f.read()
             ^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1258.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 2818: character maps to <undefined>
[11:40:36] [DEBUG] Dispatching Event: disconnect
[11:40:36] [DEBUG] Stopping the bot.
[11:40:36] [INFO] Shard ID 0 | Stopping Shard
