[11:50:23] [DEBUG] Running client sanity checks...
[11:50:23] [DEBUG] Loaded Extension: interactions.ext.jurigged
[11:50:23] [DEBUG] Added callback: __join
[11:50:23] [DEBUG] Added callback: __leave
[11:50:23] [DEBUG] Added callback: _about
[11:50:23] [DEBUG] Added callback: _setup
[11:50:23] [DEBUG] Added callback: on_start
[11:50:23] [DEBUG] 5 callbacks have been loaded from __main__.
[11:50:23] [DEBUG] Added callback: _disconnect
[11:50:23] [DEBUG] Added callback: _on_websocket_ready
[11:50:23] [DEBUG] Added callback: on_autocomplete_completion
[11:50:23] [DEBUG] Added callback: on_autocomplete_error
[11:50:23] [DEBUG] Added callback: on_command_completion
[11:50:23] [DEBUG] Added callback: on_command_error
[11:50:23] [DEBUG] Added callback: on_component_completion
[11:50:23] [DEBUG] Added callback: on_component_error
[11:50:23] [DEBUG] Added callback: on_error
[11:50:23] [DEBUG] Added callback: on_modal_completion
[11:50:23] [DEBUG] Added callback: on_modal_error
[11:50:23] [DEBUG] Added callback: on_resume
[11:50:23] [DEBUG] 12 callbacks have been loaded from Client.
[11:50:23] [DEBUG] Attempting to login
[11:50:24] [DEBUG] Caching ingested rate limit data for: 78bb8553d9352a5a2f89f9def401287a
[11:50:24] [DEBUG] GET /users/@me Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[11:50:24] [DEBUG] GET /users/@me Received 200 :: [0/1000 calls remaining]
[11:50:24] [DEBUG] Caching ingested rate limit data for: d28a133af187e91d71d96a223467ce49
[11:50:24] [DEBUG] GET /oauth2/applications/@me Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[11:50:24] [DEBUG] GET /oauth2/applications/@me Received 200 :: [0/1000 calls remaining]
[11:50:24] [WARNING] Setting sync_ext to True by default for syncing changes
[11:50:24] [INFO] Loading jurigged
[11:50:24] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\Main.py
[11:50:24] [DEBUG] GET /gateway Received 200 :: [1/1 calls remaining]
[11:50:24] [INFO] Shard ID 0 | Starting Shard
[11:50:24] [INFO] Shard ID 0 | Shard is attempting to connect to gateway...
[11:50:25] [DEBUG] Shard ID 0 | Identification payload sent to gateway, requesting intents: 3407613
[11:50:25] [INFO] Shard ID 0 | Gateway connection established
[11:50:25] [DEBUG] Shard ID 0 | Session ID: f6b055fa91dce8a3ecbf06cecd874447 Trace: ['["gateway-prd-us-east1-c-qmtk",{"micros":137786,"calls":["id_created",{"micros":1167,"calls":[]},"session_lookup_time",{"micros":1840,"calls":[]},"session_lookup_finished",{"micros":15,"calls":[]},"discord-sessions-prd-2-101",{"micros":129617,"calls":["start_session",{"micros":55717,"calls":["discord-api-dc69f8484-gwpx4",{"micros":49423,"calls":["get_user",{"micros":8595},"get_guilds",{"micros":3459},"send_scheduled_deletion_message",{"micros":12},"guild_join_requests",{"micros":890},"authorized_ip_coro",{"micros":15}]}]},"starting_guild_connect",{"micros":55,"calls":[]},"presence_started",{"micros":37252,"calls":[]},"guilds_started",{"micros":140,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":36427,"calls":[]},"connect_finished",{"micros":36432,"calls":[]},"build_ready",{"micros":18,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":0,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}]']
[11:50:25] [DEBUG] Dispatching Event: websocket_ready
[11:50:25] [DEBUG] Caching ingested rate limit data for: dd84d9818020c27975c0d5ab4a794d44
[11:50:25] [DEBUG] GET /applications/{application_id}/commands Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[11:50:25] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [0/1000 calls remaining]
[11:50:25] [DEBUG] Waiting for bucket dd84d9818020c27975c0d5ab4a794d44 to unlock.
[11:50:26] [DEBUG] Caching ingested rate limit data for: dd84d9818020c27975c0d5ab4a794d44
[11:50:26] [DEBUG] GET /applications/{application_id}/commands Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[11:50:26] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [0/1000 calls remaining]
[11:50:26] [DEBUG] 0 is already up-to-date with 15 commands.
[11:50:26] [DEBUG] Sync of 1 scopes took 0.8134932000102708 seconds
[11:50:26] [DEBUG] Dispatching Event: startup
[11:50:26] [DEBUG] Sending data to websocket: {"op": 3, "d": {"since": 1702961426307, "activities": [{"name": "/help for helpful", "type": 0}], "status": "idle", "afk": false}}
[11:50:29] [DEBUG] Sending heartbeat every 41.25 seconds
[11:50:29] [DEBUG] Sending data to websocket: {"op": 1, "d": 6}
[11:50:29] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:50:30] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:50:33] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 493, in _process_child_correspondence
    orig.apply_correspondence(
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 704, in apply_correspondence
    new_obj = self.reevaluate(corr.new.node, glb)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 801, in reevaluate
    conform(self.get_object(), new_obj)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\codefind\registry.py", line 118, in conform
    self.conform(obj1, obj2.__code__)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\codefind\registry.py", line 123, in conform
    fv1 = obj1.__code__.co_freevars
          ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '__code__'
[11:50:33] [DEBUG] Update __main__:1
[11:51:11] [DEBUG] Sending data to websocket: {"op": 1, "d": 6}
[11:51:11] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:51:11] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:51:52] [DEBUG] Sending data to websocket: {"op": 1, "d": 6}
[11:51:52] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:51:52] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:52:33] [DEBUG] Sending data to websocket: {"op": 1, "d": 6}
[11:52:33] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:52:33] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:53:14] [DEBUG] Sending data to websocket: {"op": 1, "d": 6}
[11:53:14] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:53:15] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:53:56] [DEBUG] Sending data to websocket: {"op": 1, "d": 6}
[11:53:56] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:53:56] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:54:37] [DEBUG] Sending data to websocket: {"op": 1, "d": 6}
[11:54:37] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:54:37] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:55:18] [DEBUG] Sending data to websocket: {"op": 1, "d": 6}
[11:55:18] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:55:19] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:55:24] [DEBUG] Run __main__:12 | from interactions.ext import jurigged
[11:55:24] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 480, in _process_child_correspondence
    self.evaluate_child(new)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 625, in evaluate_child
    return child.evaluate(self.get_globals(), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 245, in evaluate
    exec(code, glb, lcl)
  File "D:\Project\Python\qpneruy-Git\music\Main.py", line 13, in <adjust>
    print(jurigged.Extension.name)
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Extension' has no attribute 'name'
[11:55:24] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 493, in _process_child_correspondence
    orig.apply_correspondence(
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 704, in apply_correspondence
    new_obj = self.reevaluate(corr.new.node, glb)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 801, in reevaluate
    conform(self.get_object(), new_obj)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\codefind\registry.py", line 118, in conform
    self.conform(obj1, obj2.__code__)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\codefind\registry.py", line 123, in conform
    fv1 = obj1.__code__.co_freevars
          ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '__code__'
[11:55:24] [DEBUG] Update __main__:1
[11:55:24] [DEBUG] Dispatching Event: disconnect
[11:55:24] [DEBUG] Stopping the bot.
[11:55:24] [INFO] Shard ID 0 | Stopping Shard
