[17:33:54] [DEBUG] Running client sanity checks...
[17:33:56] [DEBUG] No setup function found in play
[17:33:56] [DEBUG] Found extension class Music in play: Attempting to load
[17:33:56] [DEBUG] Added callback: Music._menu
[17:33:56] [DEBUG] Added callback: Music._pause
[17:33:56] [DEBUG] Added callback: Music._resume
[17:33:56] [DEBUG] Added callback: Music._skip
[17:33:56] [DEBUG] Added callback: Music._stop
[17:33:56] [DEBUG] Added callback: Music.play
[17:33:56] [DEBUG] Loaded Extension: play
[17:33:56] [DEBUG] No setup function found in askgpt
[17:33:56] [DEBUG] Found extension class Gpt in askgpt: Attempting to load
[17:33:56] [DEBUG] Added callback: Gpt._askgpt
[17:33:56] [DEBUG] Added callback: Gpt._img
[17:33:56] [DEBUG] Loaded Extension: askgpt
[17:33:56] [DEBUG] No setup function found in askbard
[17:33:56] [DEBUG] Found extension class Bard in askbard: Attempting to load
[17:33:56] [DEBUG] Added callback: Bard._askbard
[17:33:56] [DEBUG] Added callback: Bard._endbard
[17:33:56] [DEBUG] Loaded Extension: askbard
[17:33:56] [DEBUG] No setup function found in noi_chu
[17:33:56] [DEBUG] Found extension class NoiChu in noi_chu: Attempting to load
[17:33:56] [DEBUG] Added callback: NoiChu._reset
[17:33:56] [DEBUG] Added callback: NoiChu._world_setup
[17:33:56] [DEBUG] Loaded Extension: noi_chu
[17:33:56] [DEBUG] No setup function found in db_refesh
[17:33:56] [DEBUG] Found extension class Database in db_refesh: Attempting to load
[17:33:56] [DEBUG] Added callback: Database.dbv1_command
[17:33:56] [DEBUG] Added callback: Database.dbv2_command
[17:33:56] [DEBUG] Loaded Extension: db_refesh
[17:33:56] [DEBUG] Added callback: __join
[17:33:56] [DEBUG] Added callback: __leave
[17:33:56] [DEBUG] Added callback: _about
[17:33:56] [DEBUG] Added callback: _help
[17:33:56] [DEBUG] Added callback: _record_channel_set
[17:33:56] [DEBUG] Added callback: _refresh
[17:33:56] [DEBUG] Added callback: _setup
[17:33:56] [DEBUG] Added callback: _starup
[17:33:56] [DEBUG] 8 callbacks have been loaded from __main__.
[17:33:56] [DEBUG] Added callback: _disconnect
[17:33:56] [DEBUG] Added callback: _on_websocket_ready
[17:33:56] [DEBUG] Added callback: on_autocomplete_completion
[17:33:56] [DEBUG] Added callback: on_autocomplete_error
[17:33:56] [DEBUG] Added callback: on_command_completion
[17:33:56] [DEBUG] Added callback: on_command_error
[17:33:56] [DEBUG] Added callback: on_component_completion
[17:33:56] [DEBUG] Added callback: on_component_error
[17:33:56] [DEBUG] Added callback: on_error
[17:33:56] [DEBUG] Added callback: on_modal_completion
[17:33:56] [DEBUG] Added callback: on_modal_error
[17:33:56] [DEBUG] Added callback: on_resume
[17:33:56] [DEBUG] 12 callbacks have been loaded from Client.
[17:33:56] [DEBUG] Attempting to login
[17:33:57] [DEBUG] Caching ingested rate limit data for: f7ead6a7674e5a323d93786263b66cb1
[17:33:57] [DEBUG] GET /users/@me Received 200 :: [49/50 calls remaining]
[17:33:57] [DEBUG] Caching ingested rate limit data for: f7ead6a7674e5a323d93786263b66cb1
[17:33:57] [DEBUG] GET /oauth2/applications/@me Received 200 :: [49/50 calls remaining]
[17:33:57] [DEBUG] Caching ingested rate limit data for: f7ead6a7674e5a323d93786263b66cb1
[17:33:57] [DEBUG] GET /gateway Received 200 :: [49/50 calls remaining]
[17:33:57] [INFO] Shard ID 0 | Starting Shard
[17:33:57] [INFO] Shard ID 0 | Shard is attempting to connect to gateway...
[17:33:58] [DEBUG] Shard ID 0 | Identification payload sent to gateway, requesting intents: 3407613
[17:33:58] [INFO] Shard ID 0 | Gateway connection established
[17:33:58] [DEBUG] Shard ID 0 | Session ID: 648b335d9ccaca1448b11318c49e246f Trace: ['["gateway-prd-us-east1-c-7j2s",{"micros":131498,"calls":["id_created",{"micros":1959,"calls":[]},"session_lookup_time",{"micros":374,"calls":[]},"session_lookup_finished",{"micros":16,"calls":[]},"discord-sessions-prd-2-188",{"micros":127887,"calls":["start_session",{"micros":71998,"calls":["discord-api-5b464978d4-gxjb9",{"micros":63268,"calls":["get_user",{"micros":6931},"get_guilds",{"micros":8156},"send_scheduled_deletion_message",{"micros":12},"guild_join_requests",{"micros":288},"authorized_ip_coro",{"micros":12}]}]},"starting_guild_connect",{"micros":73,"calls":[]},"presence_started",{"micros":321,"calls":[]},"guilds_started",{"micros":206,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":55257,"calls":[]},"connect_finished",{"micros":55264,"calls":[]},"build_ready",{"micros":21,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":0,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}]']
[17:33:58] [DEBUG] Dispatching Event: websocket_ready
[17:33:58] [DEBUG] Caching ingested rate limit data for: f7ead6a7674e5a323d93786263b66cb1
[17:33:58] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [49/50 calls remaining]
[17:33:59] [DEBUG] Caching ingested rate limit data for: f7ead6a7674e5a323d93786263b66cb1
[17:33:59] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [49/50 calls remaining]
[17:33:59] [DEBUG] 0 is already up-to-date with 19 commands.
[17:33:59] [DEBUG] Sync of 1 scopes took 0.6207999999999174 seconds
[17:33:59] [DEBUG] Dispatching Event: startup
[17:33:59] [DEBUG] Sending data to websocket: {"op": 3, "d": {"since": 1700908439124, "activities": [{"name": "l\u1ec7nh /help \u0111\u1ec3 gi\u00fap \u0111\u1ee1", "type": 0}], "status": "idle", "afk": false}}
[17:33:59] [DEBUG] Sending heartbeat every 41.25 seconds
[17:33:59] [DEBUG] Sending data to websocket: {"op": 1, "d": 6}
[17:33:59] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:33:59] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:34:00] [DEBUG] 1174695146768568424::db_refreshv1 should be called
[17:34:00] [DEBUG] Dispatching Event: command_error
[17:34:00] [DEBUG] Dispatching Event: command_completion
[17:34:00] [DEBUG] Dispatching Event: error
[17:34:00] [INFO] Command Called: db_refreshv1 with event.ctx.args = [] | event.ctx.kwargs = {}
[17:34:00] [ERROR] Ignoring exception in cmd `/db_refreshv1`:
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1900, in __dispatch_interaction
    response = await callback
               ^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1771, in _run_slash_command
    return await command(ctx, **ctx.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\command.py", line 132, in __call__
    await self.call_callback(self.callback, context)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\application_commands.py", line 802, in call_callback
    return await self.call_with_binding(callback, ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\callback.py", line 43, in call_with_binding
    return await callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Python\qpneruy-Git\music\db_refesh.py", line 84, in dbv1_command
    cursor.execute(select_query)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\connections.py", line 822, in _read_query_result
    result.read()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'discord_voice.server_data' doesn't exist")

[17:34:40] [DEBUG] Sending data to websocket: {"op": 1, "d": 7}
[17:34:40] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:34:40] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:35:21] [DEBUG] Sending data to websocket: {"op": 1, "d": 7}
[17:35:21] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:35:22] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:36:03] [DEBUG] Sending data to websocket: {"op": 1, "d": 7}
[17:36:03] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:36:03] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:36:44] [DEBUG] Sending data to websocket: {"op": 1, "d": 7}
[17:36:44] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:36:44] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:37:25] [DEBUG] Sending data to websocket: {"op": 1, "d": 7}
[17:37:25] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:37:25] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:38:06] [DEBUG] Sending data to websocket: {"op": 1, "d": 7}
[17:38:06] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:38:07] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:38:48] [DEBUG] Sending data to websocket: {"op": 1, "d": 7}
[17:38:48] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:38:48] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:39:29] [DEBUG] Sending data to websocket: {"op": 1, "d": 7}
[17:39:29] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:39:29] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:40:10] [DEBUG] Sending data to websocket: {"op": 1, "d": 7}
[17:40:10] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:40:10] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:40:51] [DEBUG] Sending data to websocket: {"op": 1, "d": 7}
[17:40:51] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:40:52] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:41:33] [DEBUG] Sending data to websocket: {"op": 1, "d": 7}
[17:41:33] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:41:33] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:41:49] [DEBUG] 1174695146768568424::db_refreshv1 should be called
[17:41:49] [DEBUG] Dispatching Event: command_error
[17:41:49] [DEBUG] Dispatching Event: command_completion
[17:41:49] [DEBUG] Dispatching Event: error
[17:41:49] [INFO] Command Called: db_refreshv1 with event.ctx.args = [] | event.ctx.kwargs = {}
[17:41:49] [ERROR] Ignoring exception in cmd `/db_refreshv1`:
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1900, in __dispatch_interaction
    response = await callback
               ^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1771, in _run_slash_command
    return await command(ctx, **ctx.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\command.py", line 132, in __call__
    await self.call_callback(self.callback, context)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\application_commands.py", line 802, in call_callback
    return await self.call_with_binding(callback, ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\callback.py", line 43, in call_with_binding
    return await callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Python\qpneruy-Git\music\db_refesh.py", line 95, in dbv1_command
    cursor.execute(insert_data_query, {'guild_id': guild.id, 'record_state': False})
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\connections.py", line 822, in _read_query_result
    result.read()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1364, "Field 'channel_id' doesn't have a default value")

[17:42:14] [DEBUG] Sending data to websocket: {"op": 1, "d": 8}
[17:42:14] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:42:14] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:42:38] [DEBUG] 1174695146768568424::db_refreshv1 should be called
[17:42:38] [DEBUG] Dispatching Event: command_error
[17:42:38] [DEBUG] Dispatching Event: command_completion
[17:42:38] [DEBUG] Dispatching Event: error
[17:42:38] [INFO] Command Called: db_refreshv1 with event.ctx.args = [] | event.ctx.kwargs = {}
[17:42:38] [ERROR] Ignoring exception in cmd `/db_refreshv1`:
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1900, in __dispatch_interaction
    response = await callback
               ^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1771, in _run_slash_command
    return await command(ctx, **ctx.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\command.py", line 132, in __call__
    await self.call_callback(self.callback, context)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\application_commands.py", line 802, in call_callback
    return await self.call_with_binding(callback, ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\callback.py", line 43, in call_with_binding
    return await callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Python\qpneruy-Git\music\db_refesh.py", line 95, in dbv1_command
    cursor.execute(insert_data_query, {'guild_id': guild.id, 'record_state': False})
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\connections.py", line 822, in _read_query_result
    result.read()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1364, "Field 'channel_id' doesn't have a default value")

[17:42:55] [DEBUG] Sending data to websocket: {"op": 1, "d": 9}
[17:42:55] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:42:55] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:43:36] [DEBUG] Sending data to websocket: {"op": 1, "d": 9}
[17:43:37] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:43:37] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:43:43] [DEBUG] 1174695146768568424::db_refreshv1 should be called
[17:43:43] [DEBUG] Caching ingested rate limit data for: 432f6223265d156004ac81366c5a948f
[17:43:43] [DEBUG] POST /interactions/{interaction_id}/aW50ZXJhY3Rpb246MTE3NzkyMjU2MzQ0ODUyNDg4MTpvRzQwNHRKUzZlbTZOdVpmU2JkWk9QUHBHRlJmc3puMFJMWFNoMVR2TU5GUEpkelI2eVpacTRrUU5aTHUwdUpGM0VPWmN5TVE5OHBNUlE1a1JNUWw0YVhZbldFWDlyYnhOQUNLT3YwaGhrWWVwTmE0bGVYODRISFRFYlJRcDhreQ/callback Received 204 :: [4/5 calls remaining]
[17:43:44] [DEBUG] Caching ingested rate limit data for: 3d2712a9e4fe17cc9d3fed4a8e672e5f
[17:43:44] [DEBUG] GET /webhooks/{application_id}/aW50ZXJhY3Rpb246MTE3NzkyMjU2MzQ0ODUyNDg4MTpvRzQwNHRKUzZlbTZOdVpmU2JkWk9QUHBHRlJmc3puMFJMWFNoMVR2TU5GUEpkelI2eVpacTRrUU5aTHUwdUpGM0VPWmN5TVE5OHBNUlE1a1JNUWw0YVhZbldFWDlyYnhOQUNLT3YwaGhrWWVwTmE0bGVYODRISFRFYlJRcDhreQ/messages/{message_id} Received 200 :: [4/5 calls remaining]
[17:43:44] [DEBUG] Dispatching Event: command_completion
[17:43:44] [INFO] Command Called: db_refreshv1 with event.ctx.args = [] | event.ctx.kwargs = {}
[17:44:18] [DEBUG] Sending data to websocket: {"op": 1, "d": 11}
[17:44:18] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:44:18] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:44:59] [DEBUG] Sending data to websocket: {"op": 1, "d": 11}
[17:44:59] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:44:59] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:45:40] [DEBUG] Sending data to websocket: {"op": 1, "d": 11}
[17:45:40] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:45:41] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:46:22] [DEBUG] Sending data to websocket: {"op": 1, "d": 11}
[17:46:22] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:46:22] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:47:03] [DEBUG] Sending data to websocket: {"op": 1, "d": 11}
[17:47:03] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:47:03] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:47:44] [DEBUG] Sending data to websocket: {"op": 1, "d": 11}
[17:47:44] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:47:44] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:48:25] [DEBUG] Sending data to websocket: {"op": 1, "d": 11}
[17:48:25] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:48:26] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:49:07] [DEBUG] Sending data to websocket: {"op": 1, "d": 11}
[17:49:07] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:49:07] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:49:48] [DEBUG] Sending data to websocket: {"op": 1, "d": 11}
[17:49:48] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:49:48] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:50:29] [DEBUG] Sending data to websocket: {"op": 1, "d": 11}
[17:50:29] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:50:29] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:51:10] [DEBUG] Sending data to websocket: {"op": 1, "d": 11}
[17:51:10] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:51:11] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:51:52] [DEBUG] Sending data to websocket: {"op": 1, "d": 11}
[17:51:52] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:51:52] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:52:33] [DEBUG] Sending data to websocket: {"op": 1, "d": 11}
[17:52:33] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:52:33] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:53:14] [DEBUG] Sending data to websocket: {"op": 1, "d": 11}
[17:53:14] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:53:14] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:53:55] [DEBUG] Sending data to websocket: {"op": 1, "d": 11}
[17:53:55] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:53:56] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:54:37] [DEBUG] Sending data to websocket: {"op": 1, "d": 11}
[17:54:37] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:54:37] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:55:18] [DEBUG] Sending data to websocket: {"op": 1, "d": 17}
[17:55:18] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[17:55:18] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[17:55:19] [DEBUG] 1177583910310379550::set_record should be called
[17:55:19] [DEBUG] Dispatching Event: command_error
[17:55:19] [DEBUG] Dispatching Event: command_completion
[17:55:19] [DEBUG] Dispatching Event: error
[17:55:19] [INFO] Command Called: set_record with event.ctx.args = [GuildVoice(id=1177925455622459434, name='record_chanel', type=<ChannelType.GUILD_VOICE: 2>)] | event.ctx.kwargs = {'channel': GuildVoice(id=1177925455622459434, name='record_chanel', type=<ChannelType.GUILD_VOICE: 2>)}
[17:55:19] [ERROR] Ignoring exception in cmd `/set_record`:
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1900, in __dispatch_interaction
    response = await callback
               ^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1771, in _run_slash_command
    return await command(ctx, **ctx.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\command.py", line 132, in __call__
    await self.call_callback(self.callback, context)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\application_commands.py", line 833, in call_callback
    return await self.call_with_binding(callback, ctx, *new_args, **new_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\callback.py", line 43, in call_with_binding
    return await callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Python\qpneruy-Git\music\Main.py", line 191, in _record_channel_set
    with pymysql.connect(host='127.0.0.1', user='root', password='', database='discord_voice') as connect_thread:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\connections.py", line 358, in __init__
    self.connect()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\connections.py", line 664, in connect
    self._request_authentication()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\connections.py", line 968, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymysql\connections.py", line 1056, in _process_auth
    raise err.OperationalError(
pymysql.err.OperationalError: (2059, "Authentication plugin 'b'auth_gssapi_client'' not configured")

[17:55:36] [DEBUG] Dispatching Event: disconnect
[17:55:36] [DEBUG] Stopping the bot.
[17:55:36] [INFO] Shard ID 0 | Stopping Shard
