[14:29:21] [DEBUG] Running client sanity checks...
[14:29:21] [DEBUG] Loaded Extension: interactions.ext.jurigged
[14:29:22] [DEBUG] No setup function found in play
[14:29:22] [DEBUG] Found extension class Music in play: Attempting to load
[14:29:22] [DEBUG] Added callback: Music._menu
[14:29:22] [DEBUG] Added callback: Music._pause
[14:29:22] [DEBUG] Added callback: Music._resume
[14:29:22] [DEBUG] Added callback: Music._skip
[14:29:22] [DEBUG] Added callback: Music._skipto
[14:29:22] [DEBUG] Added callback: Music._stop
[14:29:22] [DEBUG] Added callback: Music._viewplaylist
[14:29:22] [DEBUG] Added callback: Music.play
[14:29:22] [DEBUG] Loaded Extension: play
[14:29:22] [DEBUG] No setup function found in askbard
[14:29:22] [DEBUG] Found extension class Bard in askbard: Attempting to load
[14:29:22] [DEBUG] Added callback: Bard._askbard
[14:29:22] [DEBUG] Added callback: Bard._endbard
[14:29:22] [DEBUG] Added callback: Bard.set_bard_channel
[14:29:22] [DEBUG] Loaded Extension: askbard
[14:29:22] [DEBUG] No setup function found in noi_chu
[14:29:22] [DEBUG] Found extension class NoiChu in noi_chu: Attempting to load
[14:29:22] [DEBUG] Added callback: NoiChu._reset
[14:29:22] [DEBUG] Added callback: NoiChu._world_setup
[14:29:22] [DEBUG] Loaded Extension: noi_chu
[14:29:22] [DEBUG] No setup function found in db_refesh
[14:29:22] [DEBUG] Found extension class Database in db_refesh: Attempting to load
[14:29:22] [DEBUG] Loaded Extension: db_refesh
[14:29:22] [DEBUG] No setup function found in help
[14:29:22] [DEBUG] Found extension class Help in help: Attempting to load
[14:29:22] [DEBUG] Added callback: Help._about
[14:29:22] [DEBUG] Added callback: Help.help
[14:29:22] [DEBUG] Loaded Extension: help
[14:29:22] [DEBUG] No setup function found in channel_listen
[14:29:22] [DEBUG] Found extension class ChannelListen in channel_listen: Attempting to load
[14:29:22] [DEBUG] Added callback: ChannelListen._setup
[14:29:22] [DEBUG] Loaded Extension: channel_listen
[14:29:22] [DEBUG] Added callback: on_start
[14:29:22] [DEBUG] 1 callbacks have been loaded from __main__.
[14:29:22] [DEBUG] Added callback: _disconnect
[14:29:22] [DEBUG] Added callback: _on_websocket_ready
[14:29:22] [DEBUG] Added callback: on_autocomplete_completion
[14:29:22] [DEBUG] Added callback: on_autocomplete_error
[14:29:22] [DEBUG] Added callback: on_command_completion
[14:29:22] [DEBUG] Added callback: on_command_error
[14:29:22] [DEBUG] Added callback: on_component_completion
[14:29:22] [DEBUG] Added callback: on_component_error
[14:29:22] [DEBUG] Added callback: on_error
[14:29:22] [DEBUG] Added callback: on_modal_completion
[14:29:22] [DEBUG] Added callback: on_modal_error
[14:29:22] [DEBUG] Added callback: on_resume
[14:29:22] [DEBUG] 12 callbacks have been loaded from Client.
[14:29:22] [DEBUG] Attempting to login
[14:29:23] [DEBUG] Caching ingested rate limit data for: 78bb8553d9352a5a2f89f9def401287a
[14:29:23] [DEBUG] GET /users/@me Received 200 :: [999/1000 calls remaining]
[14:29:23] [DEBUG] Caching ingested rate limit data for: d28a133af187e91d71d96a223467ce49
[14:29:23] [DEBUG] GET /oauth2/applications/@me Received 200 :: [999/1000 calls remaining]
[14:29:23] [WARNING] Setting sync_ext to True by default for syncing changes
[14:29:23] [INFO] Loading jurigged
[14:29:23] [DEBUG] Watch D:\Project\Python\qpneruy\music\Main.py
[14:29:23] [DEBUG] Watch D:\Project\Python\qpneruy\music\play.py
[14:29:23] [DEBUG] Watch D:\Project\Python\qpneruy\music\embed.py
[14:29:23] [DEBUG] Watch D:\Project\Python\qpneruy\music\askbard.py
[14:29:23] [DEBUG] Watch D:\Project\Python\qpneruy\music\noi_chu.py
[14:29:23] [DEBUG] Watch D:\Project\Python\qpneruy\music\db_refesh.py
[14:29:23] [DEBUG] Watch D:\Project\Python\qpneruy\music\help.py
[14:29:23] [DEBUG] Watch D:\Project\Python\qpneruy\music\channel_listen.py
[14:29:23] [DEBUG] GET /gateway Received 200 :: [1/1 calls remaining]
[14:29:23] [INFO] Shard ID 0 | Starting Shard
[14:29:23] [INFO] Shard ID 0 | Shard is attempting to connect to gateway...
[14:29:23] [DEBUG] Shard ID 0 | Identification payload sent to gateway, requesting intents: 3407613
[14:29:24] [INFO] Shard ID 0 | Gateway connection established
[14:29:24] [DEBUG] Shard ID 0 | Session ID: 8e25efb32b5ab8eeefdbaa8575f1bb82 Trace: ['["gateway-prd-us-east1-b-gvzn",{"micros":192887,"calls":["id_created",{"micros":2386,"calls":[]},"session_lookup_time",{"micros":11450,"calls":[]},"session_lookup_finished",{"micros":15,"calls":[]},"discord-sessions-prd-2-190",{"micros":178615,"calls":["start_session",{"micros":61264,"calls":["discord-api-d6644f4b6-n99v6",{"micros":54287,"calls":["get_user",{"micros":7820},"get_guilds",{"micros":4617},"send_scheduled_deletion_message",{"micros":15},"guild_join_requests",{"micros":298},"authorized_ip_coro",{"micros":14}]}]},"starting_guild_connect",{"micros":72,"calls":[]},"presence_started",{"micros":32071,"calls":[]},"guilds_started",{"micros":206,"calls":[]},"guilds_connect",{"micros":3,"calls":[]},"presence_connect",{"micros":84961,"calls":[]},"connect_finished",{"micros":84970,"calls":[]},"build_ready",{"micros":28,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":1,"calls":[]},"split_ready",{"micros":0,"calls":[]}]}]}]']
[14:29:24] [DEBUG] Dispatching Event: websocket_ready
[14:29:24] [DEBUG] Dispatching Event: guild_join
[14:29:24] [DEBUG] Dispatching Event: guild_join
[14:29:24] [DEBUG] Dispatching Event: guild_join
[14:29:24] [DEBUG] Dispatching Event: guild_join
[14:29:24] [DEBUG] Dispatching Event: guild_join
[14:29:24] [DEBUG] Dispatching Event: guild_join
[14:29:24] [DEBUG] Caching ingested rate limit data for: dd84d9818020c27975c0d5ab4a794d44
[14:29:24] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [999/1000 calls remaining]
[14:29:25] [DEBUG] Caching ingested rate limit data for: dd84d9818020c27975c0d5ab4a794d44
[14:29:25] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [999/1000 calls remaining]
[14:29:25] [DEBUG] 0 is already up-to-date with 16 commands.
[14:29:25] [DEBUG] Sync of 1 scopes took 0.7538653999981761 seconds
[14:29:25] [DEBUG] Dispatching Event: startup
[14:29:25] [DEBUG] Sending data to websocket: {"op": 3, "d": {"since": 1705130965165, "activities": [{"name": "/help for helpful", "type": 0}], "status": "idle", "afk": false}}
[14:29:29] [DEBUG] 1174695146214928500::play should be called
[14:29:29] [DEBUG] Dispatching Event: message_create
[14:29:29] [DEBUG] Caching ingested rate limit data for: 432f6223265d156004ac81366c5a948f
[14:29:29] [DEBUG] POST /interactions/{interaction_id}/aW50ZXJhY3Rpb246MTE5NTYzMDY4NDExMTM3NjUxNDppUDZqaFlrdVVwdEl2bVAwQUx0T3FsT2tMTGxXMUMyaHlmWkN3cFI3TUk1SERXalpDV29pU1V6UDFwVU8ycVBwVjZTZHpiZ3doWnlpVjB3RW9oM293YW5jVjRhVHo0SEdDaXJPNnQ4eldoVHRrN0ZkaVU3NzkxcU45d2pIR3gzMw/callback Received 204 :: [4/5 calls remaining]
[14:29:29] [DEBUG] Sending data to websocket: {"op": 4, "d": {"guild_id": 1067024293709496340, "channel_id": 1195571209413349428, "self_mute": false, "self_deaf": false}}
[14:29:29] [DEBUG] Waiting for voice connection data...
[14:29:29] [DEBUG] Dispatching Event: voice_user_join
[14:29:30] [DEBUG] Attempting to initialise voice gateway...
[14:29:30] [DEBUG] Voice Connection has identified itself to Voice Gateway
[14:29:30] [DEBUG] Discord send VC Ready! Establishing a socket connection...
[14:29:30] [DEBUG] IP Discovery in progress...
[14:29:30] [DEBUG] Voice Initial Response Received: b'\x00\x02\x00F\x00\x0b\xcf2116.100.185.146\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xfa\xad'
[14:29:30] [DEBUG] IP Discovered: 116.100.185.146 #64173
[14:29:30] [DEBUG] Sending data to websocket: {"op": 1, "d": {"protocol": "udp", "data": {"address": "116.100.185.146", "port": 64173, "mode": "xsalsa20_poly1305_lite"}}}
[14:29:30] [DEBUG] Starting UDP Keep Alive
[14:29:30] [DEBUG] Unhandled OPCODE: 18 = data = {'user_id': '610841389164396565', 'flags': 2}
[14:29:30] [DEBUG] Unhandled OPCODE: 20 = data = {'user_id': '610841389164396565', 'platform': 0}
[14:29:30] [INFO] Voice connection established; using xsalsa20_poly1305_lite
[14:29:34] [DEBUG] Sending heartbeat every 41.25 seconds
[14:29:34] [DEBUG] Sending data to websocket: {"op": 1, "d": 11}
[14:29:34] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[14:29:34] [DEBUG] Sending heartbeat every 13.75 seconds
[14:29:34] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.998109749369433}
[14:29:34] [DEBUG] ❤ Voice Connection is sending Heartbeat
[14:29:34] [DEBUG] ❤ Heartbeat acknowledged after 0.06834 seconds
[14:29:35] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[14:29:35] [DEBUG] Caching ingested rate limit data for: 3d2712a9e4fe17cc9d3fed4a8e672e5f
[14:29:35] [DEBUG] PATCH /webhooks/{application_id}/aW50ZXJhY3Rpb246MTE5NTYzMDY4NDExMTM3NjUxNDppUDZqaFlrdVVwdEl2bVAwQUx0T3FsT2tMTGxXMUMyaHlmWkN3cFI3TUk1SERXalpDV29pU1V6UDFwVU8ycVBwVjZTZHpiZ3doWnlpVjB3RW9oM293YW5jVjRhVHo0SEdDaXJPNnQ4eldoVHRrN0ZkaVU3NzkxcU45d2pIR3gzMw/messages/{message_id} Received 200 :: [4/5 calls remaining]
[14:29:35] [DEBUG] Dispatching Event: message_create
[14:29:35] [DEBUG] Caching ingested rate limit data for: 3d2712a9e4fe17cc9d3fed4a8e672e5f
[14:29:35] [DEBUG] POST /webhooks/{application_id}/aW50ZXJhY3Rpb246MTE5NTYzMDY4NDExMTM3NjUxNDppUDZqaFlrdVVwdEl2bVAwQUx0T3FsT2tMTGxXMUMyaHlmWkN3cFI3TUk1SERXalpDV29pU1V6UDFwVU8ycVBwVjZTZHpiZ3doWnlpVjB3RW9oM293YW5jVjRhVHo0SEdDaXJPNnQ4eldoVHRrN0ZkaVU3NzkxcU45d2pIR3gzMw Received 200 :: [4/5 calls remaining]
[14:29:36] [DEBUG] Dispatching Event: command_error
[14:29:36] [DEBUG] Dispatching Event: command_completion
[14:29:36] [DEBUG] Dispatching Event: error
[14:29:36] [INFO] Command Called: play with event.ctx.args = ['https://www.youtube.com/playlist?list=PLL-LXY9dtjAYkB3bVI58z3FOo8U-Bckq9'] | event.ctx.kwargs = {'song': 'https://www.youtube.com/playlist?list=PLL-LXY9dtjAYkB3bVI58z3FOo8U-Bckq9'}
[14:29:36] [ERROR] Ignoring exception in cmd `/play`:
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1900, in __dispatch_interaction
    response = await callback
               ^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1771, in _run_slash_command
    return await command(ctx, **ctx.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\command.py", line 132, in __call__
    await self.call_callback(self.callback, context)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\application_commands.py", line 833, in call_callback
    return await self.call_with_binding(callback, ctx, *new_args, **new_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\callback.py", line 43, in call_with_binding
    return await callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Python\qpneruy\music\play.py", line 106, in play
    await music_queues.data_process(url_list, True)
  File "D:\Project\Python\qpneruy\modules\Music_queue.py", line 106, in data_process
    f'https://www.youtube.com/watch?v={audio["id"]}')
                                       ~~~~~^^^^^^
TypeError: 'YTDownloader' object is not subscriptable

[14:29:48] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.7679096258729792}
[14:29:48] [DEBUG] ❤ Voice Connection is sending Heartbeat
[14:29:48] [DEBUG] ❤ Heartbeat acknowledged after 0.06858 seconds
[14:29:50] [DEBUG] Dispatching Event: disconnect
[14:29:50] [DEBUG] Stopping the bot.
[14:29:50] [INFO] Shard ID 0 | Stopping Shard
[14:29:54] [DEBUG] Running client sanity checks...
[14:29:54] [DEBUG] Loaded Extension: interactions.ext.jurigged
[14:29:55] [DEBUG] No setup function found in play
[14:29:55] [DEBUG] Found extension class Music in play: Attempting to load
[14:29:55] [DEBUG] Added callback: Music._menu
[14:29:55] [DEBUG] Added callback: Music._pause
[14:29:55] [DEBUG] Added callback: Music._resume
[14:29:55] [DEBUG] Added callback: Music._skip
[14:29:55] [DEBUG] Added callback: Music._skipto
[14:29:55] [DEBUG] Added callback: Music._stop
[14:29:55] [DEBUG] Added callback: Music._viewplaylist
[14:29:55] [DEBUG] Added callback: Music.play
[14:29:55] [DEBUG] Loaded Extension: play
[14:29:55] [DEBUG] No setup function found in askbard
[14:29:55] [DEBUG] Found extension class Bard in askbard: Attempting to load
[14:29:55] [DEBUG] Added callback: Bard._askbard
[14:29:55] [DEBUG] Added callback: Bard._endbard
[14:29:55] [DEBUG] Added callback: Bard.set_bard_channel
[14:29:55] [DEBUG] Loaded Extension: askbard
[14:29:55] [DEBUG] No setup function found in noi_chu
[14:29:55] [DEBUG] Found extension class NoiChu in noi_chu: Attempting to load
[14:29:55] [DEBUG] Added callback: NoiChu._reset
[14:29:55] [DEBUG] Added callback: NoiChu._world_setup
[14:29:55] [DEBUG] Loaded Extension: noi_chu
[14:29:55] [DEBUG] No setup function found in db_refesh
[14:29:55] [DEBUG] Found extension class Database in db_refesh: Attempting to load
[14:29:55] [DEBUG] Loaded Extension: db_refesh
[14:29:55] [DEBUG] No setup function found in help
[14:29:55] [DEBUG] Found extension class Help in help: Attempting to load
[14:29:55] [DEBUG] Added callback: Help._about
[14:29:55] [DEBUG] Added callback: Help.help
[14:29:55] [DEBUG] Loaded Extension: help
[14:29:55] [DEBUG] No setup function found in channel_listen
[14:29:55] [DEBUG] Found extension class ChannelListen in channel_listen: Attempting to load
[14:29:55] [DEBUG] Added callback: ChannelListen._setup
[14:29:55] [DEBUG] Loaded Extension: channel_listen
[14:29:55] [DEBUG] Added callback: on_start
[14:29:55] [DEBUG] 1 callbacks have been loaded from __main__.
[14:29:55] [DEBUG] Added callback: _disconnect
[14:29:55] [DEBUG] Added callback: _on_websocket_ready
[14:29:55] [DEBUG] Added callback: on_autocomplete_completion
[14:29:55] [DEBUG] Added callback: on_autocomplete_error
[14:29:55] [DEBUG] Added callback: on_command_completion
[14:29:55] [DEBUG] Added callback: on_command_error
[14:29:55] [DEBUG] Added callback: on_component_completion
[14:29:55] [DEBUG] Added callback: on_component_error
[14:29:55] [DEBUG] Added callback: on_error
[14:29:55] [DEBUG] Added callback: on_modal_completion
[14:29:55] [DEBUG] Added callback: on_modal_error
[14:29:55] [DEBUG] Added callback: on_resume
[14:29:55] [DEBUG] 12 callbacks have been loaded from Client.
[14:29:55] [DEBUG] Attempting to login
[14:29:56] [DEBUG] Caching ingested rate limit data for: 78bb8553d9352a5a2f89f9def401287a
[14:29:56] [DEBUG] GET /users/@me Received 200 :: [999/1000 calls remaining]
[14:29:57] [DEBUG] Caching ingested rate limit data for: d28a133af187e91d71d96a223467ce49
[14:29:57] [DEBUG] GET /oauth2/applications/@me Received 200 :: [999/1000 calls remaining]
[14:29:57] [WARNING] Setting sync_ext to True by default for syncing changes
[14:29:57] [INFO] Loading jurigged
[14:29:57] [DEBUG] Watch D:\Project\Python\qpneruy\music\Main.py
[14:29:57] [DEBUG] Watch D:\Project\Python\qpneruy\music\play.py
[14:29:57] [DEBUG] Watch D:\Project\Python\qpneruy\music\embed.py
[14:29:57] [DEBUG] Watch D:\Project\Python\qpneruy\music\askbard.py
[14:29:57] [DEBUG] Watch D:\Project\Python\qpneruy\music\noi_chu.py
[14:29:57] [DEBUG] Watch D:\Project\Python\qpneruy\music\db_refesh.py
[14:29:57] [DEBUG] Watch D:\Project\Python\qpneruy\music\help.py
[14:29:57] [DEBUG] Watch D:\Project\Python\qpneruy\music\channel_listen.py
[14:29:57] [DEBUG] GET /gateway Received 200 :: [1/1 calls remaining]
[14:29:57] [INFO] Shard ID 0 | Starting Shard
[14:29:57] [INFO] Shard ID 0 | Shard is attempting to connect to gateway...
[14:29:57] [DEBUG] Shard ID 0 | Identification payload sent to gateway, requesting intents: 3407613
[14:29:57] [INFO] Shard ID 0 | Gateway connection established
[14:29:57] [DEBUG] Shard ID 0 | Session ID: 09cb44ccd357ca01163f9a50e62fbd3e Trace: ['["gateway-prd-us-east1-d-10rz",{"micros":63781,"calls":["id_created",{"micros":1293,"calls":[]},"session_lookup_time",{"micros":1470,"calls":[]},"session_lookup_finished",{"micros":27,"calls":[]},"discord-sessions-prd-2-132",{"micros":60721,"calls":["start_session",{"micros":59475,"calls":["discord-api-d6644f4b6-h5w8j",{"micros":53092,"calls":["get_user",{"micros":11084},"get_guilds",{"micros":5107},"send_scheduled_deletion_message",{"micros":12},"guild_join_requests",{"micros":1},"authorized_ip_coro",{"micros":14}]}]},"starting_guild_connect",{"micros":57,"calls":[]},"presence_started",{"micros":466,"calls":[]},"guilds_started",{"micros":159,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":531,"calls":[]},"connect_finished",{"micros":536,"calls":[]},"build_ready",{"micros":24,"calls":[]},"clean_ready",{"micros":0,"calls":[]},"optimize_ready",{"micros":1,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}]']
[14:29:57] [DEBUG] Dispatching Event: websocket_ready
[14:29:57] [DEBUG] Dispatching Event: guild_join
[14:29:57] [DEBUG] Dispatching Event: guild_join
[14:29:58] [DEBUG] Dispatching Event: guild_join
[14:29:58] [DEBUG] Dispatching Event: guild_join
[14:29:58] [DEBUG] Dispatching Event: guild_join
[14:29:58] [DEBUG] Dispatching Event: guild_join
[14:29:58] [DEBUG] Caching ingested rate limit data for: dd84d9818020c27975c0d5ab4a794d44
[14:29:58] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [999/1000 calls remaining]
[14:29:58] [DEBUG] Caching ingested rate limit data for: dd84d9818020c27975c0d5ab4a794d44
[14:29:58] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [999/1000 calls remaining]
[14:29:58] [DEBUG] 0 is already up-to-date with 16 commands.
[14:29:58] [DEBUG] Sync of 1 scopes took 0.732206299999234 seconds
[14:29:58] [DEBUG] Dispatching Event: startup
[14:29:58] [DEBUG] Sending data to websocket: {"op": 3, "d": {"since": 1705130998766, "activities": [{"name": "/help for helpful", "type": 0}], "status": "idle", "afk": false}}
[14:29:59] [DEBUG] Sending heartbeat every 41.25 seconds
[14:29:59] [DEBUG] Sending data to websocket: {"op": 1, "d": 7}
[14:29:59] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[14:30:00] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[14:30:02] [DEBUG] 1174695146214928500::play should be called
[14:30:03] [DEBUG] Dispatching Event: message_create
[14:30:03] [DEBUG] Caching ingested rate limit data for: 432f6223265d156004ac81366c5a948f
[14:30:03] [DEBUG] POST /interactions/{interaction_id}/aW50ZXJhY3Rpb246MTE5NTYzMDgyNDM0NzkyNjU0OTo0Z0NRc0RBTFNFOVhuS29uMDRsZEtUVmtZQjZxajlzeEtPUlhSZmhtZUpqekJlY3FYbWpOSkl4QnVZWUxqNnZwbmtrNkFxMW5CWm8yNTdDZ3ZtaW5ndHZIbkVoOXJsU2ZBTlNoZUdaSVpZQTdZTjFySkw2NlRzSnc5TzVHWE9ERw/callback Received 204 :: [4/5 calls remaining]
[14:30:03] [DEBUG] Sending data to websocket: {"op": 4, "d": {"guild_id": 1067024293709496340, "channel_id": 1195571209413349428, "self_mute": false, "self_deaf": false}}
[14:30:03] [DEBUG] Waiting for voice connection data...
[14:30:03] [DEBUG] Dispatching Event: voice_user_join
[14:30:03] [DEBUG] Attempting to initialise voice gateway...
[14:30:03] [DEBUG] Voice Connection has identified itself to Voice Gateway
[14:30:03] [DEBUG] Discord send VC Ready! Establishing a socket connection...
[14:30:03] [DEBUG] IP Discovery in progress...
[14:30:03] [DEBUG] Voice Initial Response Received: b'\x00\x02\x00F\x00\x0b\xcf@116.100.185.146\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xc9^'
[14:30:03] [DEBUG] IP Discovered: 116.100.185.146 #51550
[14:30:03] [DEBUG] Sending data to websocket: {"op": 1, "d": {"protocol": "udp", "data": {"address": "116.100.185.146", "port": 51550, "mode": "xsalsa20_poly1305_lite"}}}
[14:30:03] [DEBUG] Starting UDP Keep Alive
[14:30:03] [DEBUG] Unhandled OPCODE: 18 = data = {'user_id': '610841389164396565', 'flags': 2}
[14:30:03] [DEBUG] Unhandled OPCODE: 20 = data = {'user_id': '610841389164396565', 'platform': 0}
[14:30:03] [INFO] Voice connection established; using xsalsa20_poly1305_lite
[14:30:08] [DEBUG] Sending heartbeat every 13.75 seconds
[14:30:08] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.2208062237026749}
[14:30:08] [DEBUG] ❤ Voice Connection is sending Heartbeat
[14:30:08] [DEBUG] ❤ Heartbeat acknowledged after 0.06913 seconds
[14:30:08] [DEBUG] Caching ingested rate limit data for: 3d2712a9e4fe17cc9d3fed4a8e672e5f
[14:30:08] [DEBUG] PATCH /webhooks/{application_id}/aW50ZXJhY3Rpb246MTE5NTYzMDgyNDM0NzkyNjU0OTo0Z0NRc0RBTFNFOVhuS29uMDRsZEtUVmtZQjZxajlzeEtPUlhSZmhtZUpqekJlY3FYbWpOSkl4QnVZWUxqNnZwbmtrNkFxMW5CWm8yNTdDZ3ZtaW5ndHZIbkVoOXJsU2ZBTlNoZUdaSVpZQTdZTjFySkw2NlRzSnc5TzVHWE9ERw/messages/{message_id} Received 200 :: [4/5 calls remaining]
[14:30:09] [DEBUG] Dispatching Event: message_create
[14:30:09] [DEBUG] Caching ingested rate limit data for: 3d2712a9e4fe17cc9d3fed4a8e672e5f
[14:30:09] [DEBUG] POST /webhooks/{application_id}/aW50ZXJhY3Rpb246MTE5NTYzMDgyNDM0NzkyNjU0OTo0Z0NRc0RBTFNFOVhuS29uMDRsZEtUVmtZQjZxajlzeEtPUlhSZmhtZUpqekJlY3FYbWpOSkl4QnVZWUxqNnZwbmtrNkFxMW5CWm8yNTdDZ3ZtaW5ndHZIbkVoOXJsU2ZBTlNoZUdaSVpZQTdZTjFySkw2NlRzSnc5TzVHWE9ERw Received 200 :: [4/5 calls remaining]
[14:30:10] [DEBUG] Dispatching Event: command_error
[14:30:10] [DEBUG] Dispatching Event: command_completion
[14:30:10] [DEBUG] Dispatching Event: error
[14:30:10] [INFO] Command Called: play with event.ctx.args = ['https://www.youtube.com/playlist?list=PLL-LXY9dtjAYkB3bVI58z3FOo8U-Bckq9'] | event.ctx.kwargs = {'song': 'https://www.youtube.com/playlist?list=PLL-LXY9dtjAYkB3bVI58z3FOo8U-Bckq9'}
[14:30:10] [ERROR] Ignoring exception in cmd `/play`:
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1581, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1716, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\youtube.py", line 4175, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 1196, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] videoplayba: Video unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1900, in __dispatch_interaction
    response = await callback
               ^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1771, in _run_slash_command
    return await command(ctx, **ctx.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\command.py", line 132, in __call__
    await self.call_callback(self.callback, context)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\application_commands.py", line 833, in call_callback
    return await self.call_with_binding(callback, ctx, *new_args, **new_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\callback.py", line 43, in call_with_binding
    return await callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Python\qpneruy\music\play.py", line 106, in play
    await music_queues.data_process(url_list, True)
  File "D:\Project\Python\qpneruy\modules\Music_queue.py", line 105, in data_process
    avatar_url = await self.VideoData.get_uploader_avt(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Python\qpneruy\modules\Music_queue.py", line 55, in get_uploader_avt
    data = self.youtube_dl.extract_info(url, download=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1570, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1599, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1048, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 987, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [youtube] videoplayba: Video unavailable

[14:30:22] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.469079385041135}
[14:30:22] [DEBUG] ❤ Voice Connection is sending Heartbeat
[14:30:22] [DEBUG] ❤ Heartbeat acknowledged after 0.09923 seconds
[14:30:35] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.12796280412054262}
[14:30:35] [DEBUG] ❤ Voice Connection is sending Heartbeat
[14:30:35] [DEBUG] ❤ Heartbeat acknowledged after 0.07650 seconds
[14:30:38] [DEBUG] 1174695146214928500::play should be called
[14:30:38] [DEBUG] Dispatching Event: message_create
[14:30:38] [DEBUG] Caching ingested rate limit data for: 432f6223265d156004ac81366c5a948f
[14:30:38] [DEBUG] POST /interactions/{interaction_id}/aW50ZXJhY3Rpb246MTE5NTYzMDk3NDUwNDAyMjA5Njo1UXZCQ29wQ2F3R1VsZ3NZTm9zZVptTUhBTHVGR01BTnluYjRoZk9xdzZYY25UQXN4c1V1WFBJaHM0WlJWcmNKdzhKYzhtN3hJY3dRdjJyU0VYdGxFaTNLSXREeXV4V01tQ244MlBkZUFUeGc2R2hnZWdzb1RmT2ZzNGx5V3JLNA/callback Received 204 :: [4/5 calls remaining]
[14:30:42] [DEBUG] Sending data to websocket: {"op": 1, "d": 15}
[14:30:42] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[14:30:43] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[14:30:43] [DEBUG] Caching ingested rate limit data for: 3d2712a9e4fe17cc9d3fed4a8e672e5f
[14:30:43] [DEBUG] PATCH /webhooks/{application_id}/aW50ZXJhY3Rpb246MTE5NTYzMDk3NDUwNDAyMjA5Njo1UXZCQ29wQ2F3R1VsZ3NZTm9zZVptTUhBTHVGR01BTnluYjRoZk9xdzZYY25UQXN4c1V1WFBJaHM0WlJWcmNKdzhKYzhtN3hJY3dRdjJyU0VYdGxFaTNLSXREeXV4V01tQ244MlBkZUFUeGc2R2hnZWdzb1RmT2ZzNGx5V3JLNA/messages/{message_id} Received 200 :: [4/5 calls remaining]
[14:30:43] [DEBUG] Dispatching Event: message_create
[14:30:43] [DEBUG] Caching ingested rate limit data for: 3d2712a9e4fe17cc9d3fed4a8e672e5f
[14:30:43] [DEBUG] POST /webhooks/{application_id}/aW50ZXJhY3Rpb246MTE5NTYzMDk3NDUwNDAyMjA5Njo1UXZCQ29wQ2F3R1VsZ3NZTm9zZVptTUhBTHVGR01BTnluYjRoZk9xdzZYY25UQXN4c1V1WFBJaHM0WlJWcmNKdzhKYzhtN3hJY3dRdjJyU0VYdGxFaTNLSXREeXV4V01tQ244MlBkZUFUeGc2R2hnZWdzb1RmT2ZzNGx5V3JLNA Received 200 :: [4/5 calls remaining]
[14:30:44] [DEBUG] Dispatching Event: command_error
[14:30:44] [DEBUG] Dispatching Event: command_completion
[14:30:44] [DEBUG] Dispatching Event: error
[14:30:44] [INFO] Command Called: play with event.ctx.args = ['https://www.youtube.com/playlist?list=PLL-LXY9dtjAYkB3bVI58z3FOo8U-Bckq9'] | event.ctx.kwargs = {'song': 'https://www.youtube.com/playlist?list=PLL-LXY9dtjAYkB3bVI58z3FOo8U-Bckq9'}
[14:30:44] [ERROR] Ignoring exception in cmd `/play`:
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1581, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1716, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\youtube.py", line 4175, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 1196, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] videoplayba: Video unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1900, in __dispatch_interaction
    response = await callback
               ^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1771, in _run_slash_command
    return await command(ctx, **ctx.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\command.py", line 132, in __call__
    await self.call_callback(self.callback, context)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\application_commands.py", line 833, in call_callback
    return await self.call_with_binding(callback, ctx, *new_args, **new_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\callback.py", line 43, in call_with_binding
    return await callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Python\qpneruy\music\play.py", line 106, in play
    await music_queues.data_process(url_list, True)
  File "D:\Project\Python\qpneruy\modules\Music_queue.py", line 105, in data_process
    avatar_url = await self.VideoData.get_uploader_avt(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Python\qpneruy\modules\Music_queue.py", line 55, in get_uploader_avt
    data = self.youtube_dl.extract_info(url, download=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1570, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1599, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1048, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 987, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [youtube] videoplayba: Video unavailable

[14:30:49] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.12705850363745563}
[14:30:49] [DEBUG] ❤ Voice Connection is sending Heartbeat
[14:30:49] [DEBUG] ❤ Heartbeat acknowledged after 0.06870 seconds
[14:31:03] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.45175482990215665}
[14:31:03] [DEBUG] ❤ Voice Connection is sending Heartbeat
[14:31:03] [DEBUG] ❤ Heartbeat acknowledged after 0.07596 seconds
[14:31:17] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.5900810608950671}
[14:31:17] [DEBUG] ❤ Voice Connection is sending Heartbeat
[14:31:17] [DEBUG] ❤ Heartbeat acknowledged after 0.13538 seconds
[14:31:24] [DEBUG] Sending data to websocket: {"op": 1, "d": 17}
[14:31:24] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[14:31:24] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[14:31:30] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.5402538816826877}
[14:31:30] [DEBUG] ❤ Voice Connection is sending Heartbeat
[14:31:30] [DEBUG] ❤ Heartbeat acknowledged after 0.06896 seconds
[14:31:44] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.38499459200808983}
[14:31:44] [DEBUG] ❤ Voice Connection is sending Heartbeat
[14:31:44] [DEBUG] ❤ Heartbeat acknowledged after 0.07029 seconds
[14:31:58] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.5638336150965685}
[14:31:58] [DEBUG] ❤ Voice Connection is sending Heartbeat
[14:31:58] [DEBUG] ❤ Heartbeat acknowledged after 0.07688 seconds
[14:32:05] [DEBUG] Sending data to websocket: {"op": 1, "d": 17}
[14:32:05] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[14:32:05] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[14:32:12] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.4481228090153395}
[14:32:12] [DEBUG] ❤ Voice Connection is sending Heartbeat
[14:32:12] [DEBUG] ❤ Heartbeat acknowledged after 0.07743 seconds
[14:32:25] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.1088375376111036}
[14:32:25] [DEBUG] ❤ Voice Connection is sending Heartbeat
[14:32:25] [DEBUG] ❤ Heartbeat acknowledged after 0.07760 seconds
[14:32:39] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.554241407606734}
[14:32:39] [DEBUG] ❤ Voice Connection is sending Heartbeat
[14:32:39] [DEBUG] ❤ Heartbeat acknowledged after 0.07496 seconds
[14:32:46] [DEBUG] Sending data to websocket: {"op": 1, "d": 17}
[14:32:46] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[14:32:46] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[14:32:53] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.16998432574974287}
[14:32:53] [DEBUG] ❤ Voice Connection is sending Heartbeat
[14:32:53] [DEBUG] ❤ Heartbeat acknowledged after 0.09234 seconds
[14:32:54] [DEBUG] Dispatching Event: disconnect
[14:32:54] [DEBUG] Stopping the bot.
[14:32:54] [INFO] Shard ID 0 | Stopping Shard
