[11:57:28] [DEBUG] Running client sanity checks...
[11:57:28] [DEBUG] Loaded Extension: interactions.ext.jurigged
[11:57:30] [DEBUG] No setup function found in play
[11:57:30] [DEBUG] Found extension class Music in play: Attempting to load
[11:57:30] [DEBUG] Added callback: Music._menu
[11:57:30] [DEBUG] Added callback: Music._pause
[11:57:30] [DEBUG] Added callback: Music._resume
[11:57:30] [DEBUG] Added callback: Music._skip
[11:57:30] [DEBUG] Added callback: Music._stop
[11:57:30] [DEBUG] Added callback: Music.play
[11:57:30] [DEBUG] Loaded Extension: play
[11:57:31] [DEBUG] No setup function found in askbard
[11:57:31] [DEBUG] Found extension class Bard in askbard: Attempting to load
[11:57:31] [DEBUG] Added callback: Bard._askbard
[11:57:31] [DEBUG] Added callback: Bard._endbard
[11:57:31] [DEBUG] Added callback: Bard.set_bard_channel
[11:57:31] [DEBUG] Loaded Extension: askbard
[11:57:31] [DEBUG] No setup function found in noi_chu
[11:57:31] [DEBUG] Found extension class NoiChu in noi_chu: Attempting to load
[11:57:31] [DEBUG] Added callback: NoiChu._reset
[11:57:31] [DEBUG] Added callback: NoiChu._world_setup
[11:57:31] [DEBUG] Loaded Extension: noi_chu
[11:57:31] [DEBUG] No setup function found in db_refesh
[11:57:31] [DEBUG] Found extension class Database in db_refesh: Attempting to load
[11:57:31] [DEBUG] Loaded Extension: db_refesh
[11:57:31] [DEBUG] No setup function found in help
[11:57:31] [DEBUG] Found extension class Help in help: Attempting to load
[11:57:31] [DEBUG] Added callback: Help.help
[11:57:31] [DEBUG] Loaded Extension: help
[11:57:31] [DEBUG] Added callback: __join
[11:57:31] [DEBUG] Added callback: __leave
[11:57:31] [DEBUG] Added callback: _about
[11:57:31] [DEBUG] Added callback: _setup
[11:57:31] [DEBUG] Added callback: on_start
[11:57:31] [DEBUG] 5 callbacks have been loaded from __main__.
[11:57:31] [DEBUG] Added callback: _disconnect
[11:57:31] [DEBUG] Added callback: _on_websocket_ready
[11:57:31] [DEBUG] Added callback: on_autocomplete_completion
[11:57:31] [DEBUG] Added callback: on_autocomplete_error
[11:57:31] [DEBUG] Added callback: on_command_completion
[11:57:31] [DEBUG] Added callback: on_command_error
[11:57:31] [DEBUG] Added callback: on_component_completion
[11:57:31] [DEBUG] Added callback: on_component_error
[11:57:31] [DEBUG] Added callback: on_error
[11:57:31] [DEBUG] Added callback: on_modal_completion
[11:57:31] [DEBUG] Added callback: on_modal_error
[11:57:31] [DEBUG] Added callback: on_resume
[11:57:31] [DEBUG] 12 callbacks have been loaded from Client.
[11:57:31] [DEBUG] Attempting to login
[11:57:31] [DEBUG] Caching ingested rate limit data for: 78bb8553d9352a5a2f89f9def401287a
[11:57:31] [DEBUG] GET /users/@me Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[11:57:31] [DEBUG] GET /users/@me Received 200 :: [0/1000 calls remaining]
[11:57:32] [DEBUG] Caching ingested rate limit data for: d28a133af187e91d71d96a223467ce49
[11:57:32] [DEBUG] GET /oauth2/applications/@me Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[11:57:32] [DEBUG] GET /oauth2/applications/@me Received 200 :: [0/1000 calls remaining]
[11:57:32] [WARNING] Setting sync_ext to True by default for syncing changes
[11:57:32] [INFO] Loading jurigged
[11:57:32] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\Main.py
[11:57:32] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\play.py
[11:57:32] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\embed.py
[11:57:32] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\askbard.py
[11:57:32] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\noi_chu.py
[11:57:32] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\db_refesh.py
[11:57:32] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\help.py
[11:57:32] [DEBUG] Caching ingested rate limit data for: 0a6d458104b103c7be293cc9b284d9ee
[11:57:32] [DEBUG] GET /gateway Received 200 :: [99/100 calls remaining]
[11:57:32] [INFO] Shard ID 0 | Starting Shard
[11:57:32] [INFO] Shard ID 0 | Shard is attempting to connect to gateway...
[11:57:32] [DEBUG] Shard ID 0 | Identification payload sent to gateway, requesting intents: 3407613
[11:57:33] [INFO] Shard ID 0 | Gateway connection established
[11:57:33] [DEBUG] Shard ID 0 | Session ID: 026f828a383fa5f293fcbe72bfa4ae49 Trace: ['["gateway-prd-us-east1-c-vg5x",{"micros":209947,"calls":["id_created",{"micros":2146,"calls":[]},"session_lookup_time",{"micros":13510,"calls":[]},"session_lookup_finished",{"micros":15,"calls":[]},"discord-sessions-prd-2-41",{"micros":193514,"calls":["start_session",{"micros":150397,"calls":["discord-api-dc69f8484-8pt6z",{"micros":132223,"calls":["get_user",{"micros":55134},"get_guilds",{"micros":7396},"send_scheduled_deletion_message",{"micros":15},"guild_join_requests",{"micros":4212},"authorized_ip_coro",{"micros":14}]}]},"starting_guild_connect",{"micros":65,"calls":[]},"presence_started",{"micros":16985,"calls":[]},"guilds_started",{"micros":149,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":25887,"calls":[]},"connect_finished",{"micros":25893,"calls":[]},"build_ready",{"micros":23,"calls":[]},"clean_ready",{"micros":0,"calls":[]},"optimize_ready",{"micros":0,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}]']
[11:57:33] [DEBUG] Dispatching Event: websocket_ready
[11:57:33] [DEBUG] Dispatching Event: guild_join
[11:57:33] [DEBUG] Dispatching Event: guild_join
[11:57:33] [DEBUG] Dispatching Event: guild_join
[11:57:33] [DEBUG] Dispatching Event: guild_join
[11:57:33] [DEBUG] Dispatching Event: guild_join
[11:57:33] [DEBUG] Caching ingested rate limit data for: dd84d9818020c27975c0d5ab4a794d44
[11:57:33] [DEBUG] GET /applications/{application_id}/commands Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[11:57:33] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [0/1000 calls remaining]
[11:57:33] [DEBUG] Waiting for bucket dd84d9818020c27975c0d5ab4a794d44 to unlock.
[11:57:33] [DEBUG] Caching ingested rate limit data for: dd84d9818020c27975c0d5ab4a794d44
[11:57:33] [DEBUG] GET /applications/{application_id}/commands Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[11:57:33] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [0/1000 calls remaining]
[11:57:33] [DEBUG] 0 is already up-to-date with 15 commands.
[11:57:33] [DEBUG] Sync of 1 scopes took 0.7321142000000691 seconds
[11:57:33] [DEBUG] Dispatching Event: startup
[11:57:33] [DEBUG] Sending data to websocket: {"op": 3, "d": {"since": 1702961853902, "activities": [{"name": "/help for helpful", "type": 0}], "status": "idle", "afk": false}}
[11:57:48] [DEBUG] Sending heartbeat every 41.25 seconds
[11:57:48] [DEBUG] Sending data to websocket: {"op": 1, "d": 6}
[11:57:48] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:57:48] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:58:29] [DEBUG] Sending data to websocket: {"op": 1, "d": 6}
[11:58:29] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:58:29] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:59:10] [DEBUG] Sending data to websocket: {"op": 1, "d": 6}
[11:59:10] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:59:10] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:59:26] [DEBUG] Dispatching Event: voice_user_join
[11:59:26] [DEBUG] Caching ingested rate limit data for: be56019ae011689ff5baf218062aacf5
[11:59:26] [DEBUG] POST /guilds/1067024293709496340/channels Received 201 :: [1998/2000 calls remaining]
[11:59:27] [DEBUG] Caching ingested rate limit data for: 6e836da6cef38ba2f3dfd8568a4e9631
[11:59:27] [DEBUG] PATCH /channels/1186533228438372422 Received 200 :: [9/10 calls remaining]
[11:59:27] [DEBUG] Shard ID 0 | No processor for `raw_channel_topic_update`
[11:59:27] [DEBUG] Shard ID 0 | No processor for `raw_voice_channel_status_update`
[11:59:27] [DEBUG] Caching ingested rate limit data for: c7f060a5d9790cb6f53000110a7b7edf
[11:59:27] [DEBUG] PATCH /guilds/1067024293709496340/members/{user_id} Received 200 :: [9/10 calls remaining]
[11:59:35] [DEBUG] Caching play
[11:59:36] [DEBUG] Update play.Music.play:71
[11:59:36] [DEBUG] Update play.Music:47
[11:59:36] [DEBUG] Update play:1
[11:59:36] [DEBUG] Update play.Music.play:71
[11:59:36] [DEBUG] Update play.Music:47
[11:59:36] [DEBUG] Update play:1
[11:59:36] [DEBUG] Checking play
[11:59:36] [DEBUG] Checking for changes
[11:59:36] [DEBUG] No changes detected
[11:59:51] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 493, in _process_child_correspondence
    orig.apply_correspondence(
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 704, in apply_correspondence
    new_obj = self.reevaluate(corr.new.node, glb)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 801, in reevaluate
    conform(self.get_object(), new_obj)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\codefind\registry.py", line 118, in conform
    self.conform(obj1, obj2.__code__)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\codefind\registry.py", line 123, in conform
    fv1 = obj1.__code__.co_freevars
          ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '__code__'
[11:59:51] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 493, in _process_child_correspondence
    orig.apply_correspondence(
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 704, in apply_correspondence
    new_obj = self.reevaluate(corr.new.node, glb)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 801, in reevaluate
    conform(self.get_object(), new_obj)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\codefind\registry.py", line 118, in conform
    self.conform(obj1, obj2.__code__)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\codefind\registry.py", line 123, in conform
    fv1 = obj1.__code__.co_freevars
          ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '__code__'
[11:59:51] [DEBUG] Update __main__:1
[11:59:51] [DEBUG] Add __main__.__leave:121
[11:59:51] [DEBUG] Add __main__._setup:140
[11:59:51] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 480, in _process_child_correspondence
    self.evaluate_child(new)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 625, in evaluate_child
    return child.evaluate(self.get_globals(), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 245, in evaluate
    exec(code, glb, lcl)
  File "D:\Project\Python\qpneruy-Git\music\Main.py", line 154, in <adjust>
    bot.load_extension("play")
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 2003, in load_extension
    raise Exception(f"{module_name} already loaded")
Exception: play already loaded
[11:59:51] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 480, in _process_child_correspondence
    self.evaluate_child(new)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 625, in evaluate_child
    return child.evaluate(self.get_globals(), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 245, in evaluate
    exec(code, glb, lcl)
  File "D:\Project\Python\qpneruy-Git\music\Main.py", line 155, in <adjust>
    bot.load_extension("askbard")
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 2003, in load_extension
    raise Exception(f"{module_name} already loaded")
Exception: askbard already loaded
[11:59:51] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 480, in _process_child_correspondence
    self.evaluate_child(new)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 625, in evaluate_child
    return child.evaluate(self.get_globals(), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 245, in evaluate
    exec(code, glb, lcl)
  File "D:\Project\Python\qpneruy-Git\music\Main.py", line 156, in <adjust>
    bot.load_extension("noi_chu")
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 2003, in load_extension
    raise Exception(f"{module_name} already loaded")
Exception: noi_chu already loaded
[11:59:51] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 480, in _process_child_correspondence
    self.evaluate_child(new)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 625, in evaluate_child
    return child.evaluate(self.get_globals(), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 245, in evaluate
    exec(code, glb, lcl)
  File "D:\Project\Python\qpneruy-Git\music\Main.py", line 157, in <adjust>
    bot.load_extension("db_refesh")
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 2003, in load_extension
    raise Exception(f"{module_name} already loaded")
Exception: db_refesh already loaded
[11:59:51] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 480, in _process_child_correspondence
    self.evaluate_child(new)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 625, in evaluate_child
    return child.evaluate(self.get_globals(), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 245, in evaluate
    exec(code, glb, lcl)
  File "D:\Project\Python\qpneruy-Git\music\Main.py", line 158, in <adjust>
    bot.load_extension("help")
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 2003, in load_extension
    raise Exception(f"{module_name} already loaded")
Exception: help already loaded
[11:59:51] [DEBUG] Listener <Listener event='voice_user_join' callback=<function __join at 0x0000024C26213C40>> has already been hooked, not re-hooking it again
[11:59:51] [DEBUG] Added callback: __join
[11:59:51] [DEBUG] Added callback: __leave
[11:59:51] [ERROR] Jurigged encountered an error
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 480, in _process_child_correspondence
    self.evaluate_child(new)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 625, in evaluate_child
    return child.evaluate(self.get_globals(), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\jurigged\codetools.py", line 245, in evaluate
    exec(code, glb, lcl)
  File "D:\Project\Python\qpneruy-Git\music\Main.py", line 160, in <adjust>
    bot.start(Token)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 993, in start
    asyncio.run(self.astart(token))
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 949, in astart
    await self.login(token)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 923, in login
    self._gather_callbacks()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1420, in _gather_callbacks
    process(main_commands, "__main__")
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1406, in process
    self.add_command(func)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1379, in add_command
    self.add_interaction(func)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1294, in add_interaction
    raise ValueError(f"Duplicate Command! {scope}::{old_cmd.resolved_name}")
ValueError: Duplicate Command! 0::about
[11:59:51] [DEBUG] Update __main__:1
[11:59:51] [DEBUG] Sending data to websocket: {"op": 1, "d": 15}
[11:59:51] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:59:52] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[12:00:14] [DEBUG] Dispatching Event: disconnect
[12:00:14] [DEBUG] Stopping the bot.
[12:00:14] [INFO] Shard ID 0 | Stopping Shard
